#!/usr/bin/env python

__author__ = "Mehmood Alam Khan"
__email__  = "malagori@kth.se"
__version__= "0.9"
__license__ = "GPL"
__credits__ = ["Mehmood Alam Khan", "Pekka Parviainen"]

import os
import sys
import argparse

from bayesInfer.mainAlgo import MainAlgo


def runMainAlgo(vdFile, dataFile, outdir, alpha, seed, steepestAsent,iterations, seedFile, outPutFile, simulatedAnealingFlag, decrementValue, pertTowRecFlag, mlabPath ):
    
    objMainAlgo = MainAlgo(vdFile, dataFile, outdir, alpha, seed, steepestAsent,iterations, seedFile, outPutFile, simulatedAnealingFlag, decrementValue, pertTowRecFlag, mlabPath)
    objMainAlgo.runAlgo()



def checkFile(filePath):
        return os.path.isfile(os.path.abspath(filePath)) 


def checkDir(dirPath):
        return os.path.isdir(dirPath) and os.access(dirPath, os.X_OK)
    
def findMatlabLibDir():
    for p in os.environ["PATH"].split(os.pathsep):
        #p=os.path.dirname(p)
        if p:
            tok=[]
            tok= p.split('/')
            if tok[-1] == "matlab_lib":
                if checkDir(p):
                    return p   
    return None

def main(argv):
    
     
    # Take care of input
    parser = argparse.ArgumentParser(description="Parse input arguments and print output.")
    parser.add_argument('-vd', metavar='vdFile' ,type=str, help='Specify path to the file containing variable information ')
    parser.add_argument('-d', metavar='dataFile',type=str, help='Specify path to the data file ')
    parser.add_argument('-a', metavar='alpha',type=float , help='Specify alpha parameter ', default=1.0)
    parser.add_argument('-sa', dest='SteepestAsent',action="store_true", help='Steepest Asent is used if set to True ')
    parser.add_argument('-sim', dest='SimAnnealing',action="store_true", help='Simulated Annealing is used if set to True ')
    parser.add_argument('-i', metavar='iterations',type=int , help='Specify maximum number of iterations ', default=100000)
    parser.add_argument('-dc', metavar='decrementValue',type=int , help='Specify the decrement value ', default=1)
    parser.add_argument('-s', metavar='initialSeed',type=int , help='Specify initial seed. if both initialSeed and loadseed option are not provided then system time will be taken as the default seed  ', default=None)
    parser.add_argument('-l', metavar='loadSeed',type=str , help='Specify path to a file containing previous state', default=None)
    parser.add_argument('-o', metavar='outFile', type=str, help='Specify the file to output the results. ', default= 'fuv_results.txt')
    parser.add_argument('-od', metavar='outDir', type=str, help='Specify Path to the directory to write the results. ', default= 'fuv_dir_results')
    parser.add_argument('-p', dest='perturbTwoRecods',action="store_true", help='Uses two-record- perturbation function if set to True')
    parser.add_argument('-hx', dest='excludeHidBDeu',action="store_true", help='BDeu score for hidden variable will be excluded from total bnt score if set to True ')
    
    
    args = parser.parse_args()
    
    vdFile          = args.vd
    outdir          = args.od
    dataFile        = args.d
    alpha           = args.a
    seed            = args.s
    steepestAsent   = args.SteepestAsent
    seedFile        = args.l
    outPutFile      = args.o
    iterations      = args.i
    simAnealFlag    = args.SimAnnealing
    decrementValue  = args.dc
    pertTowRecFlag  = args.perturbTwoRecods
    exHiddenBdeuFlag= args.excludeHidBDeu

    
    
    print "vdfile:             %s"  % vdFile
    print "Directory:          %s"  % outdir
    print "dataFile:           %s"  % dataFile
    print "alpha:              %f"  % alpha 
    if pertTowRecFlag == True:
        print "pertTowRecFlag %s" % (pertTowRecFlag)
    if exHiddenBdeuFlag == True:
        print "exHiddenBdeuFlag %s" % (exHiddenBdeuFlag)
    if seed != None:
        print "seed:                %d" % seed
    print "outPutFile:                %s" % outPutFile
    
    
    mlabPath= findMatlabLibDir()
    vdPath= checkFile(vdFile)
    if  vdPath != True:
        print "Error: Path to vd file is not correct"
        sys.exit()
        
    if checkFile(dataFile) != True:
        print "Error: Path to data file is not correct"
        sys.exit()
    
    if mlabPath != None:
        runMainAlgo(vdFile, dataFile, outdir, alpha, seed, steepestAsent, iterations, seedFile, outPutFile, simAnealFlag, decrementValue, pertTowRecFlag, mlabPath)
    else:
        print "Error: Path to matlab_lib folder is not set"
        sys.exit()
    
if __name__== "__main__":
    if not sys.argv[1:]:
        print "Type: fuv --help"
        sys.exit()
    main(sys.argv[1:])